# Generated by Django 4.2.1 on 2023-05-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
    ]
