# Generated by Django 4.2.1 on 2023-05-23 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_generatedaccountnumber_alter_user_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedaccountnumber',
            name='account_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='generatedaccountnumber',
            name='account_type',
            field=models.CharField(choices=[('Fixed Deposit', 'Fixed Deposit'), ('Savings', 'Savings'), ('Current', 'Current'), ('Dormant', 'Dormant')], default='Savings', max_length=100),
        ),
        migrations.AlterField(
            model_name='generatedaccountnumber',
            name='bank_branch_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Routine Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_branch_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Routine Number'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('reference', models.CharField(default='', max_length=100)),
                ('transfer_type', models.CharField(default='', max_length=100)),
                ('sender_email', models.CharField(default='', max_length=100)),
                ('receiver_name', models.CharField(default='', max_length=100)),
                ('receiver_bank_name', models.CharField(default='', max_length=100)),
                ('receiver_account_number', models.CharField(default='', max_length=100)),
                ('routine_number', models.CharField(blank=True, default='', max_length=100)),
                ('bank_branch_code', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
