# Generated by Django 4.2.1 on 2023-05-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_generatedaccountnumber_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
