# Generated by Django 4.2.1 on 2023-05-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_transaction_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='OTP'),
        ),
    ]
